"""added allocate role in workspacealloc

Revision ID: 3769335d1b2b
Revises: 98112664af93
Create Date: 2026-07-07 19:02:09.394261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3769335d1b2b'
down_revision: Union[str, Sequence[str], None] = '98112664af93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspacealloc', sa.Column('allocated_role', sa.Enum('owner', 'creator', 'sub_creator', name='role_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspacealloc', 'allocated_role')
    # ### end Alembic commands ###
